<?xml version="1.0" encoding="utf-8"?><Database Name="Security" Class="SecurityDataSetDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLExpress;Initial Catalog=Security;Integrated Security=True" SettingsObjectName="Tie.UnitTest.NET4.Properties.Settings" SettingsPropertyName="SecurityConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Person_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="User_Name" Type="System.String" DbType="NVarChar(256) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Plain_Password" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Password" Type="System.Data.Linq.Binary" DbType="VarBinary(64)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Inactive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Middle_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nickname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Group_Name" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Job_Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="WorkPhone" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="WorkFax" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="WorkPager" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="WorkMobile" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="Signature" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Avatar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Password_Changed_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Logon_Locked_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Start_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="End_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Date_Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Creator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date_Modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifier" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRoles" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Role_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date_Expired" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Date_Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Creator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date_Modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifier" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="Role_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Role_Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Parent_Role_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date_Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Creator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date_Modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifier" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>